#url: "https://gawdtech-tools.github.io"
#baseurl: "/RustDesk-Web"

title: RustDesk
description: Remote desktop.


client:
  title: RustDesk Web Client
  version: 1.4.4
  buildNumber: 62
  buildDate: "2025-11-19 11:40"
  custom_config: ""


firebase:
  apiKey: "AIzaSyCgehIZk1aFP0E7wZtYRRqrfvNiNAF39-A"
  authDomain: "rustdesk.firebaseapp.com"
  databaseURL: "https://rustdesk.firebaseio.com"
  projectId: "rustdesk"
  storageBucket: "rustdesk.appspot.com"
  messagingSenderId: "768133699366"
  appId: "1:768133699366:web:d50faf0792cb208d7993e7"
  measurementId: "G-9PEH85N6ZQ"
